# Site settings
title: Tucson Women in Data Science (WIDS) Conference 2020 
email: bhurwitz@email.arizona.edu 
description: > # this means to ignore newlines until "baseurl:"
  Tucson WIDS Meeting 2020
#baseurl: "/2020-meeting"
#url: "https://wids-tucson.github.io"

# Build settings
markdown: kramdown

assets:
  sources:
    - assets/fonts
    - assets/images
    - assets/js
    - assets/css

gems:
  - jekyll-assets


theme: jekyll-theme-time-machine
